### ISSUE TITLE
[Bug]: Bundle failed to be deployed with libjuju

### ISSUE THREAD

**Issue by gcalvinos** [juju/python-libjuju#733]
### Description

When trying to deploy the bundle attached with libjuju, the deployment fails with the following error:

```
2022-09-15T09:02:03 ERROR lcm.ns ns.py:4803 Task ns=dfb67747-3bc1-47ed-a61e-a752345fc1f2 instantiate=01541df7-9b19-4d64-9ce4-41ef39128fa0 Deploying KDU magma-orc-kdu Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/osm_lcm/ns.py", line 3316, in _install_kdu
    await self.k8scluster_map[k8sclustertype].install(
  File "/usr/lib/python3/dist-packages/n2vc/k8s_juju_conn.py", line 358, in install
    await libjuju.deploy(bundle, model_name=namespace, wait=atomic, timeout=timeout)
  File "/usr/lib/python3/dist-packages/n2vc/libjuju.py", line 565, in deploy
    await model.deploy(uri, trust=True)
  File "/usr/local/lib/python3.8/dist-packages/juju/model.py", line 1616, in deploy
    await handler.execute_plan()
  File "/usr/local/lib/python3.8/dist-packages/juju/bundle.py", line 380, in execute_plan
    self.references[step.id_] = await change.run(self)
  File "/usr/local/lib/python3.8/dist-packages/juju/bundle.py", line 609, in run
    resources = await context.model._add_charmhub_resources(
  File "/usr/local/lib/python3.8/dist-packages/juju/model.py", line 1762, in _add_charmhub_resources
    res = await charm_facade.CharmInfo(entity_url)
  File "/usr/local/lib/python3.8/dist-packages/juju/client/facade.py", line 501, in wrapper
    result = cls.from_json(reply['response'])
  File "/usr/local/lib/python3.8/dist-packages/juju/client/facade.py", line 672, in from_json
    return cls(**d)
  File "/usr/local/lib/python3.8/dist-packages/juju/client/_definitions.py", line 4800, in __init__
    meta_ = CharmMeta.from_json(meta) if meta else None
  File "/usr/local/lib/python3.8/dist-packages/juju/client/facade.py", line 672, in from_json
    return cls(**d)
  File "/usr/local/lib/python3.8/dist-packages/juju/client/_definitions.py", line 5312, in __init__
    assumes_expr_ = ExpressionTree.from_json(assumes_expr) if assumes_expr else None
  File "/usr/local/lib/python3.8/dist-packages/juju/client/facade.py", line 668, in from_json
    for k, v in (data or {}).items():
AttributeError: 'list' object has no attribute 'items'
```
But the bundle is deployed properly when using juju client.

[magma-orc-bundle.txt](https://github.com/juju/python-libjuju/files/9575089/magma-orc-bundle.txt)

### Urgency

Annoying bug in our test suite

### Python-libjuju version

2.9.11

### Juju version

2.9.34

### Reproduce / Test

```python
Python libjuju is used inside OSM
```

**Comment by cderici** [comment]
This should be fixed by https://github.com/juju/python-libjuju/pull/685, closing the issue #684 that looks quite similar to this one. That PR is in the `pylibjuju 2.9.11` release. However, @gcalvinos noted that they might be using `2.9.10`. We can close this one if that's the case.

**Comment by gcalvinos** [comment]
Looks like the issue also happen in 2.9.11. I updated the juju version in the container, but I still get the same error.

```
root@lcm-646d4f9fd7-p6269:/app/N2VC# pip3 list | grep juju
juju               2.9.11
jujubundlelib      0.5.7
```

**Comment by cderici** [comment]
This is also fixed by https://github.com/juju/python-libjuju/pull/696, upgrading to `3.0.0` (or latest) hopefully will solve these problems :+1:

**Comment by gcalvinos** [comment]
Upgrading to 3.0.0 solved the issue
